Feature: 21 components part 5
CryptoHiveNet/crypto-web pull request #41
Opened 2024-04-28 14:45 UTC by sepehrsohrabii

**Background**
The components will be completed in these kinds of issues.

**Description**
The developed components contain card, datepicker, and dropdown.
Wrote unit tests for all of them.
One of the important tasks in this issue was to refactor all component files in the way that adds the flowbite-react component types for the project's components.
In addition, component folder names have been changed to the exact component name.

**Expected behavior**
The expected behavior is that the components work correctly in any situation.

**Observed behavior**
The expected behavior was observed correctly.

**How to reproduce/test**
All of the components can be tested by running the test command.

2024-04-28 20:02 UTC, haghighi251 requested changes
@sepehrsohrabii  Please do these changes in all of the files and MRs so I don't need to write them in each file for you and also am able to approve them. Thanks.

2024-04-28 20:02 UTC, haghighi251 commented on src/app/[lng]/components-test/page.tsx
> -import Alert from '@/types/components/alert/Alert';
Why do we have this component here? Please remove it. If you want to test something you can do it by usnit test. If you want to see it on the screen you can add it in the page.tsx and after checking, it must be removed.

2024-04-28 20:02 UTC, haghighi251 commented on src/app/[lng]/layout.spec.tsx
>      expect(metadata.title).toBe('Create Next App');
Don't use hard code in the test files. Add them to the translation file.

2024-04-28 20:02 UTC, haghighi251 commented on src/app/[lng]/layout.spec.tsx
>      expect(metadata.description).toBe('Generated by create next app');
Please add all strings like this in the translation file. We call text values from translation file in the component and also on the test.

2024-04-28 20:02 UTC, haghighi251 commented on src/app/[lng]/layout.spec.tsx
> +      getServerSessionMock.mockRestore();
There is no test for your changes like fonts!

2024-04-28 20:02 UTC, haghighi251 commented on src/app/[lng]/layout.tsx
>  import { Roboto, Vazirmatn } from 'next/font/google';
It should be mocked in the test file:
`jest.mock(''next/font/google'')`

2024-04-28 20:02 UTC, haghighi251 commented on src/app/[lng]/layout.tsx
>  import { Roboto, Vazirmatn } from 'next/font/google';
vazirmatn and robot should be in a separate file and get imported here. I'll do it myself but try to not add variables like this in a file that make that file messy. Please always add them in a ts file and import them in the origin file.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.tsx
> +const Accordion = forwardRef<any, iAccordionProps>(
You need add this comment before forwardRef: 
`// eslint-disable-next-line react/display-name`
Didn't you have esLinter errors red line?

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.tsx
> +import { iAccordionProps } from '@/types/types/components/accordion';
lower i should be used when we want to use an interface not data type with type. If we are gonna use type, we should use NameProps for props data type.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.tsx
> +    }: iAccordionProps,
Please don't use this style: 
`export type iAccordionItemProps = {
  titleClassName?: string;
  contentClassName?: string;
  title: string;
  content: ReactNode;
} & UserReactionProps &
  BaseProps;` 
  
  now if you go to see the iAccordionProps in the Accordion component you will see this in the ide:
  `type iAccordionProps = AccordionProps & UserReactionProps & BaseProps` 
  
  I didn't like it. I didn't like it because we are not able to see the parameters with the desired data type and I have to open the file in which the iAccordionProps is declared to see its parameters which is not good. I should be able to see these parameters from the component directly when I move the mouse on the iAccordionProps word otherwise I'd lose a lot of time in developing to open and see the data types and keep them in my mind and backing to the component and trying to get some evaluation done in my head. I need to see them directly in the component file.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/AccordionItem/AccordionItem.spec.tsx
> +import { iAccordionItemProps } from '@/types/types/components/accordion';
WE shouldn't have any error/warning in the console when we run a test or the application. Please remove this error:
` Warning: React does not recognize the `alwaysOpen` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `alwaysopen` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

If you run the test you can see it.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.spec.tsx
> +  it('should call the onClick handler when clicked (if provided)', () => {
should call the onClick handler when clicked if provided

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.spec.tsx
> +    const { getByTestId } = render(<Accordion {...props} />);
Use a better name.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.spec.tsx
> +  const defaultProps = {
Please always put this kind of variables in the public scop which is before the describe.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.spec.tsx
> +  it('should render the FlowbiteAccordion component with passed props', () => {
Accordion component ....

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.spec.tsx
> +  const props: iAccordionProps = {
Why is this here? You can remove it.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/Accordion.spec.tsx
> +  it('renders without crashing', () => {
WE don't need these tests here and could be moved into this test: 
should render the Accordion component with passed props

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Accordion/AccordionItem/AccordionItem.tsx
> +const AccordionItem = forwardRef<any, iAccordionItemProps>(
// eslint-disable-next-line react/display-name

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Alert/Alert.tsx
> +          if (onDismiss) {
Please never repeat commands! Add this method and call it here: 
`const disMissHandler = () => {
      if (onDismiss) {
        if (typeof onDismiss === 'function') {
          onDismiss();
        } else {
          onDismiss;
        }
      }
    }`

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Alert/Alert.tsx
> +      if (onDismiss) {
disMissHandler

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Avatar/Avatar.spec.tsx
> +      expect(getByText('Test Children')).toBeInTheDocument();
If you have something in the test file which is not a translation part and is going to be used in a test file, you can make a mock json/ts/js file in the global __mock__ folder and call them from there!

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Avatar/AvatarCounter/AvatarCounter.spec.tsx
> +  // Test case 1: Renders the component with required props
Remove chatGPT comments.

2024-04-28 20:02 UTC, haghighi251 commented on src/components/Avatar/AvatarGroup/AvatarGroup.spec.tsx
> +  // Test case 1: Renders the component with required props
remove comments like this when they're not useful/necessary.

2024-04-29 07:08 UTC, sepehrsohrabii commented on src/app/[lng]/components-test/page.tsx
> -import Alert from '@/types/components/alert/Alert';
Yes, you are right. I removed the components-test route totally.

2024-05-11 14:04 UTC, sepehrsohrabii commented
This PR doesn't need to be merged. this was merged into another PR before.

2024-05-11 14:18 UTC, closed without merging