Fix: PR41 splitting part 11
CryptoHiveNet/crypto-web pull request #53
Opened 2024-05-01 08:20 UTC by sepehrsohrabii

Modified spinner and table components.

2024-05-04 14:26 UTC, sepehrsohrabii commented on src/components/textBox/TextBox.tsx
Please don't check this file because it is modified in another PR.

2024-05-04 16:37 UTC, haghighi251 requested changes

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Table/TableRow/TableRow.spec.tsx
> +        <Table>
It should be in the it function not in the public scop of the test unless you have some tests that are using the same data.

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Table/TableHeadCell/TableHeadCell.spec.tsx
> +    const mockProps = {
Put them into the it function not in the global scop.

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Table/TableHead/TableHead.spec.tsx
> +        className: 'custom-table-head',
Render must be in the it function and also the mock data should be outside of the describe function.

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Table/TableCell/TableCell.spec.tsx
> +    };
Render must be in the it function and also the mock data should be outside of the describe function.

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Table/TableBody/TableBody.spec.tsx
> +    const mockProps = {
Render must be in the it function and also the mock data should be outside of the describe function.

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Table/Table.spec.tsx
> +    const mockProps = {
Render must be in the it function and also the mock data should be outside of the describe function.

2024-05-04 16:37 UTC, haghighi251 commented on src/components/Spinner/Spinner.spec.tsx
> +    const mockProps = {
Render must be in the it function and also the mock data should be outside of the describe function.

2024-05-11 10:03 UTC, merged

2024-05-11 10:04 UTC, haghighi251 commented
@sepehrsohrabii Please check the last commit I did.